c:
	cat exploit/c1.txt | ./hex2raw | ./ctarget -q
	cat exploit/c2.txt | ./hex2raw | ./ctarget -q
	cat exploit/c3.txt | ./hex2raw | ./ctarget -q
r:
	cat exploit/r2.txt | ./hex2raw | ./rtarget -q
	cat exploit/r3.txt | ./hex2raw | ./rtarget -q
